# 베이스 이미지를 도커 허브에서 가져옴
FROM node:alpine

# 해당 어플의 소스 코드들이 들어감
WORKDIR /app

# 소스 코드가 바뀔 때마다 종속성까지 다시 복사를 해주는 수고를 하지 않기 위해
# 먼저 종속성 목록 담고 있는 package.json 복사
COPY package.json ./

# package.json에 명시된 종속성 다운
RUN npm install

# 이제는 모든 소스 코드들을 WORKDIR로 복사
COPY ./ ./

# 이 컨테이너가 실행될 때 같이 실행할 명령어 지정
CMD [ "npm", "run", "start" ]